### PR TITLE
Add events page

### PR DESCRIPTION
**Pull request by xsharonhe**
I added a few things:
- Completed the events page
- Made events slugs possible so you can access on ```localhost:3000/events/pump-plus``` for example and will have to keep in touch to create more
- Added some facts on QuickFacts

I started Board Members but didn't complete so ignore that file for now.

### CODE REVIEW

**Review by hirundinidae — DISMISSED** [review]
Looks good! Just a couple of things: 
1. Smaller margins on mobile 
- card content margin stays about the same across screen widths, -> do you think smaller margins would look good? 
- decrease margin above the section title 
- the sections take up a whole screen of mobile 
image

2. (small thing) quick facts carousel
- I think this is because there's no text, but the arrows to move the slides look too close to the bottom of the cardImage 
- or there's extra space below the cardImage treated as carousel height (remove -> arrows shift up as centered in the carousel height) 
screenshot_20210802_153116

Each events section on wider screens doesn't eventually change to the `text on left + carousel on right` but I think it looks better without becoming 2 columns. 

Otherwise, the rest looks good :] just up to you if you want to change ^

**Review by hirundinidae — APPROVED** [review]
Looks **great** to me! :+1:

**Comment by jilly477** [comment]
lgtm!

**Review by jilly477 — COMMENTED** [review]
lgtm!

**Pull request merged**
